services:
  - type: web
    name: worldcup-multi-agent
    runtime: docker
    rootDir: Frontend-Deployment-Production
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: OPENROUTER_API_KEY
        sync: false   # أنت هتحطه يدوياً في Render Dashboard
    healthCheckPath: /health
